global:
  username: "Not Richard"
  
schedule:
  meeting_shift_min: 2
  job_shift_min: 1

morning:
  alarm: "11:00"
  city: "Malmsheim"
  origin: "Weil der Stadt"
  destination: "Malmsheim"

joke:
  times:
    - "22:02"
    - "22:02"
    - "22:02"
    - "22:04"
  blacklist:
    - "nsfw"
    - "religious"
    - "political"
    - "racist"
    - "sexist"
    - "explicit"

time:
  reminder_time: 20

cooking:
  times:
    - "17:09"
  artist:
    - "Eminem"
    - "Imagine Dragons"
