global:
  username: "Daniel"

morning:
  alarm: "11:00"
  city: "Malmsheim"
  origin: "Weil der Stadt"
  destination: "Malmsheim"

joke:
  times:
    - "10:15"
    - "16:23"
    - "17:30"
    - "19:21"
  blacklist:
    - "nsfw"
    - "religious"
    - "political"
    - "racist"
    - "sexist"
    - "explicit"
