global:
  username: "Daniel"

morning:
  alarm: "12:50"
  city: "Stuttgart"
  origin: "Gropiusplatz 5 Stuttgart"
  destination: "DHBW Fakultät Technik Stuttgart"

joke:
  times:
    - "12:53"
    - "16:23"
    - "17:30"
    - "19:21"
  blacklist:
    - "nsfw"
    - "religious"
    - "political"
    - "racist"
    - "sexist"
    - "explicit"
